import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import NavBar from "@/components/common/NavBar";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Exit Polling App",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children }: Readonly<{ children: React.ReactNode }>
) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <section className="mt-8">
            <main role="main">
              {/* <p className="info"><%= get_flash(@conn, :info) %></p>
              <p className="error"><%= get_flash(@conn, :error) %></p> */}
              { children }
            </main>
          </section>
        </Providers>
      </body>
    </html>
  );
}
